<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'statistics_general'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>一般统计</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="twoCloumn clearfix">
            <ul>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日新增会员</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">今日新增会员</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日VIP订单</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">今日VIP订单</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日新增社团</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">今日新增社团</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">今日短信订单</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">今日小秘书订单</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">未处理求助小秘书</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">未处理举报</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">待审核社团</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">待审核党建</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">待审核广告</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">待审核VIP链接</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">新的意见建议</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">新的咨询客服</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日活动数量</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日供求数量</div><div class="rightText">32</div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>