<div class="headLogo tac">
        	<img src="/admin/images/logo.fw.png">
       	    <p class="p22 mt10">友好后台管理登录</p>
        </div>
	<div class="login">        
        <form class="color576 tal mt30">
        	<div class="formList">
            	<div class="formListL tar">账号:</div>
                <div class="formListR">
                	<input type="text" placeholder="请输入账号" class="normalInput">
                </div>
            </div>
            <div class="formList">
            	<div class="formListL tar">密码:</div>
                <div class="formListR">
                	<input type="text" placeholder="请输入账号" class="normalInput">
                </div>
            </div>
            <div class="formList">
            	<div class="formListR tar">
            	<a href="index.html" class="mainBtn">
                	登录
                </a>
                </div>
            </div>
        </form>
    </div>