<link href="/web/js/plugins/swiper/swiper-3.3.1.min.css" rel="stylesheet" type="text/css">
<style>
    .leftNav{width: 100%;height: 100px;padding-left: 30px;}
    .pl{padding-left: 60px;}
</style>
<div class="leftNav left">
    <form id="form">
        <div class="formList">
            <div class="formListL">名称:</div>
            <div class="formListR">
                <input type="text" placeholder="请输入账号" class="" name="title">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">地址:</div>
            <div class="formListR">
                <input type="text" placeholder="请输入地址" class="" name="url">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">唯一标识:</div>
            <div class="formListR">
                <input type="text" placeholder="请输入唯一标识" class="" name="point">
            </div>
        </div>
        <div class="formList">
            <div class="formListR">
                <a href="javascript:void(0);" class="mainBtn" role="submit">确定</a>
            </div>
        </div>
    </form>
</div>

<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {
                var id = '<?php echo (isset($id) && $id) ? $id : '';?>';
                if(id)
                {
                        var datas = <?php echo json_encode($data, JSON_UNESCAPED_UNICODE)?>;
                        $('form').setFormValue(datas);
                }else
                {
                        var parent_id = '<?php echo $pid;?>';
                }
                $('.leftNav').delegate('a[role]', 'click', function () {
                        var $this = $(this),
                                role = $this.attr('role');
                        switch (role) {
                                case'add':
                                        openIframe({
                                            url: 'http://ddshou.cn',
                                            title: '保存'
                                        });
                                        break;
                                case 'submit':
                                        var data = getFormValue($('#form')),msg = '';
                                        if (!data.title)
                                        {
                                                msg = '请先选择要删除的数据';
                                        } else if(!data.url)
                                        {
                                                msg = '请先选择要删除的数据';
                                        } else if(!data.point)
                                        {
                                                msg = '请先选择要删除的数据';
                                        }
                                        if(msg)
                                        {
                                                Tips('error', msg);
                                        } else {
                                                data.model = <?php echo $model;?>;
                                                if(id)
                                                {
                                                        data.id = id;
                                                } else
                                                {
                                                        data.parent_id = parent_id;
                                                }
                                                alert($.toJSON(data));
                                                rpcJSON('nav', data, function (backData) {
                                                    Tips('success', '添加成功', 1000, function () {
                                                            parent.location.reload();
                                                    });
                                                }, function (msg) {
                                                    Tips('error', msg);
                                                }, '/admin/navrpc');
                                        }
                                        break;
                        }
                });
        });
</script>