<link href="/web/js/plugins/swiper/swiper-3.3.1.min.css" rel="stylesheet" type="text/css">
<style>
    .leftNav{width: 100%;height: 100%;padding-left: 30px;}
    .pl{padding:10px 0 10px 60px;}
</style>
<?php

function treeHtml($data)
{
        $html .= '';
        foreach ($data as $key => $value)
        {
                $html .= '<div data-id="' . $value['id'] . '" class="pl left" role="id">
                                <div style="display: block;float: right">
                                        <a href="javascript:;" role="add">添加</a>
                                        <a href="javascript:;" role="edit">编辑</a>
                                        <a href="javascript:;" role="del">删除</a>
                                </div>' . $value['title'];
                if (isset($value['child']) && $value['child'])
                {
                        $html .= treeHtml($value['child']);
                }
                $html .= '</div>';
        }
        return $html;
}
?>
<div class="leftNav left">
    <div style="width: 100%;line-height: 20px;"><a href="javascript:;" role="addNav">添加</a></div>
    <div>
        <?php echo treeHtml($data); ?>
    </div>
</div>

<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {
                var rpcUrl = '/admin/navrpc',url='/admin/nav/addNav';
                $('.leftNav').delegate('a[role]', 'click', function () {
                        var $this = $(this),
                                role = $this.attr('role'),
                                id = $this.parents('div[role="id"]:first').data('id');
                        switch (role) {
                                case'add':
                                        url = url + '?model=1&pid=' + id;
                                        alert(url);
                                        openIframe({
                                                url: url,
                                                title: '添加'
                                        });
                                        break;
                                case'addNav':
                                        url = url + '?model=1&pid=' + 0;
                                        openIframe({
                                                url: url,
                                                title: '添加'
                                        });
                                        break;
                                case 'edit':
                                        url = url + '?model=1&id=' + id;
                                        openIframe({
                                                url: url,
                                                title: '编辑'
                                        });
                                        break;
                                case 'del':
                                        rpcJSON('del', {id: id, model: 2}, function (backData) {
                                                Tips('success', '删除成功', 1000, function () {
                                                    window.location.reload();
                                                });
                                        }, function (msg) {
                                                Tips('error', msg);
                                        }, rpcUrl);
                                        break;
                        }
                });
        });
</script>