<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'ad_order', 'in' => 'ad'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>添加广告</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">            
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">指定用户</div>
                <div class="formListR">
                    <input class="inputNormal" placeholder="用户账号">
                </div>
            </div>
            <div class="formList">
                <div class="formListL">广告位置</div>
                <div class="formListR">
                    <select>
                        <option>消息首页</option>
                        <option>消息-搜索</option>
                        <option>发现首页</option>
                        <option>发现-人脉</option>
                        <option>发现-社团</option>
                        <option>发现-活动</option>
                        <option>发现-供求</option>
                        <option>发现-更</option>
                    </select>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">广告图片</div>
                <div class="formListR">
                    <div class="companyPic">
                        <img src="/admin/images/ioserwei.png">
                    </div>
                    <a href="javascript:;" class="addBtn"><i class="icon-add"></i></a>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">广告标题</div>
                <div class="formListR">
                    <input class="inputNormal" placeholder="" value="">
                </div>
            </div>
            <div class="formList">
                <div class="formListL">跳转链接</div>
                <div class="formListR">
                    <input class="inputNormal" placeholder="" value="http://">
                </div>
            </div>
            <div class="formList">
                <div class="formListL">发布地区</div>
                <div class="formListR">
                    <select>
                        <option>选择地区</option>
                    </select>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">起始时间</div>
                <div class="formListR">
                    <input class="inputNormal" placeholder="" value="">
                    <span class="color999">—</span>
                    <input class="inputNormal" placeholder="" value="">
                </div>
            </div>
            <div class="formList">
                <div class="formListL">费用</div>
                <div class="formListR">
                    500元
                </div>
            </div>
            <div class="formList mt20">
                <a href="javascript:;" class="mainBtn">确定</a>
            </div>
        </div>
    </div>
</div>