<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'top_order', 'in' => 'ad'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>置顶订单</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="topBar clearfix"><!--筛选栏-->
            <div class="screenBar">
                <div class="screenBtn">
                    <a href="javascript:;">批量操作</a>
                    <div class="screenBox">
                        <li>批量删除</li>
                    </div>
                </div>
                <div class="screenBtn">
                    <a href="javascript:;">全部位置</a>
                    <div class="screenBox">
                        <li>消息首页</li>
                        <li>消息-搜索</li>
                        <li>发现首页</li>
                        <li>发现-人脉</li>
                        <li>发现-社团</li>
                        <li>发现-活动</li>
                        <li>发现-供求</li>
                        <li>发现-更多</li>
                    </div>
                </div>
                <div class="screenBtn overlength">
                    <a href="javascript:;">排序</a>
                    <div class="screenBox">
                        <li>按发布时间排序（近到远）</li>
                        <li>按到期时间排序（近到远）</li>
                    </div>
                </div>
                <div class="searchBar fl">
                    <input type="text" placeholder="请输入搜索内容">
                    <a href="javascript:;" class="searchBtn">搜索</a>
                </div>
            </div>

        </div><!--筛选栏结束-->
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th width="40px"><label><input type="checkbox"><div class="select"></div></label></th>
                        <th>订单编号</th>
                        <th>订单名称</th>
                        <th>发布人账号</th>
                        <th>类型</th>
                        <th>置顶地区</th>
                        <th>置顶起止时间</th>
                        <th>置顶价格</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td width="40px"><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>111</td>
                        <td>订单1</td>
                        <td>1380000000</td>
                        <td>活动</td>
                        <td>浙江杭州，上海，北京</td>
                        <td><p>始：2016/12/12</p><p>末：2016/12/12</p></td>
                        <td>120.00元</td>                    
                        <td><a href="前台活动页面">查看</a><a href="javascript:;">停止</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td width="40px"><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>111</td>
                        <td>订单1</td>
                        <td>1380000000</td>
                        <td>活动</td>
                        <td>浙江杭州，上海，北京</td>
                        <td><p>始：2016/12/12</p><p>末：2016/12/12</p></td>
                        <td>120.00元</td>                    
                        <td><a href="前台活动页面">查看</a><a href="javascript:;">停止</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td width="40px"><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>111</td>
                        <td>订单1</td>
                        <td>1380000000</td>
                        <td>活动</td>
                        <td>浙江杭州，上海，北京</td>
                        <td><p>始：2016/12/12</p><p>末：2016/12/12</p></td>
                        <td>120.00元</td>                    
                        <td><a href="前台活动页面">查看</a><a href="javascript:;">停止</a><a href="javascript:;">删除</a></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="pageBar">
            <div class="page fr">
                <ul class="clearfix">
                    <li><a href="javascript:;"><i class="icon-left"></i></a></li>
                    <li><a href="javascript:;" class="active">1</a></li>
                    <li><a href="javascript:;">2</a></li>
                    <li><a href="javascript:;">3</a></li>
                    <li><a href="javascript:;">4</a></li>
                    <li><a href="javascript:;"><i class="icon-right"></i></a></li>
                </ul>
            </div>
            <div class="pageBar_num fl"><p class="sFc">共<span class="lFc">2</span>条数据，每页显示
                    <select>
                        <option>10</option>
                    </select>
                    <span>条数据</span>
                </p>
            </div>
        </div>
    </div>
</div>