<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'top_price', 'in' => 'ad'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>置顶位广告价格（天数×元/天/人）</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">            
        <div class="editInfo overlength clearfix">
            <div class="formList">
                <div class="formListL">每人每天价格</div>
                <div class="formListR"><input type="text" class="msgInput" value=""><span class="ml10">元/天/人</span></div>                    
            </div>
            <div class="formList mt20">
                <a href="javascript:;" class="mainBtn">确定</a>
            </div>
        </div>
    </div>
</div>