<style>
    .photo{width: 100px;height: 100px}
</style>
<div class="login">
    <div class="wrapper">
        <div class="lineText"><span class="red">登录</span></div>
        <form class="color576 tal mt30" id="form">
            <div class="formList">
                <div class="formListL tar">账号:</div>
                <div class="formListR">
                    <input type="text" placeholder="请输入账号" class="normalInput" name="account">
                </div>
            </div>
            <div class="formList">
                <div class="formListL tar">密码:</div>
                <div class="formListR">
                    <input type="password" placeholder="请输入账号" class="normalInput" name="password">
                </div>
            </div>
            <div class="formList">
                <div class="formListR tar">
                    <a href="javascript:void(0);" class="mainBtn" role="submit">登录</a>
                </div>
            </div>

            <div class="loginRow loginRowTips">
                <a class="fr" href="/person/findpwd">忘记密码？</a>
                <span><label><input type="checkbox" name="rememberPassword"/>记住密码</label></span>
            </div>
            <a href="/register/index" class="h5 mt10 tac display_b">还没有账号，免费注册</a>
        </form>
    </div>
    <div>
        <img src="<?php echo $this->config->upload->url.'14840199092805433.jpg'?>" class="photo"/>
        <img src="<?php echo $this->config->upload->url.'14840199092805433.jpg'?>" class="photo"/>
        <img src="<?php echo $this->config->upload->url.'14840199092805433.jpg'?>" class="photo"/>
    </div>
</div>

<?php
$this->partial("commen/footer");
?>
<script>
        (function ($) {

            if ($.cookie("rmbUser") == "true") {
                $('input[name="rememberPassword"]').prop("checked", true);
                var account = $.cookie("account"),
                        password = $.cookie("password");
                $('input[name="account"]').val(account);
                $('input[name="password"]').val(password);


            }
            ;
            setTimeout(function () {
                $('.markBox input').each(function () {
                    if (!$(this).val()) {
                        $(this).siblings('.mark').show();
                    }
                    ;
                });
            }, 500);
            var checkLogin = function () {
                rpcJSON('checkWxLogin', {wxMark: '<?php echo $wxMark; ?>'}, function () {
                    window.location.href = getURL();
                }, function (msg) {
                }, '/userrpc');
            };
            timeid = setInterval(function () {
                checkLogin();
            }, 2000);

            var vcodeURL = '/login/vcode?',
                    rpcURL = '/userrpc',
                    form = $('#form'),
                    onSucess = function () {
                        window.location.href = getURL();
                    },
                    formSubmit = function () {
                        var value = getFormValue(form),
                                msg = '';
                        if (!value.account) {
                            msg = '账号不能为空';
                        } else if (value.password.length < 6 || value.password.length > 24) {
                            msg = '密码应为6-24位字符';
                        }
                        ;

                        if (msg) {
                            Tips('error', msg);
                        } else {
                            rpcJSON('signIn', value, function (backData) {
                                //记住密码
                                if ($('input[name="rememberPassword"]').prop("checked")) {
                                    $.cookie("rmbUser", "true", {expires: 7, path: '/'});
                                    $.cookie("password", value.password, {expires: 7, path: '/'});
                                    $.cookie("account", value.account, {expires: 7, path: '/'});
                                } else {
                                    $.cookie("rmbUser", "false", {expires: 7, path: '/'});
                                }
                                ;
                                Tips('success', '登录成功，正在为您跳转', 1500, function () {
                                    onSucess();
                                });
                            }, function (msg) {
                                Tips('error', msg);
                                $('input[name="vcode"]', form).val('');
                            }, rpcURL);
                        }
                    };

            $(document).keydown(function (event) {
                if (event.keyCode == 13) {
                    formSubmit();
                }
            });



            form.delegate('a[role]', click, function (e) {
                var $this = $(this);
                switch ($this.attr('role')) {
                    case 'submit':
                        formSubmit();
                        break;
                    case 'wx':
                        if (isWeixin) {
                            window.location.href = '<?php echo $wxUrl; ?>';
                        } else {
                            var html =
                                    '<div class="tac"><p><img style="width:200px" src="/login/wxQrcode?wxMark=<?php echo $wxMark; ?>" /></p><p>&nbsp</P></div>';
                            Dialog(html, {
                                title: '请您使用微信扫描二维码登录',
                                width: 350,
                                cancelText: '',
                                closeText: '×',
                                confirmText: ''
                            });
                        }
                        ;
                        break;
                }
            });


            function getURL() {
                var ref = '';
                if (document.referrer.length > 0 && document.referrer.indexOf('ddshou') >= 0) {
                    ref = document.referrer;
                } else {
                    ref = '/index/index';
                }
                ;
                if (document.referrer.indexOf('/register/') >= 0 || document.referrer.indexOf('/login/') >= 0 || document.referrer.indexOf('/person/') >= 0) {
                    ref = '/person/index';
                }
                ;
                return ref;
            }
            ;
            $('.markBox input').change(function () {
                if ($(this).val()) {
                    $(this).siblings('.mark').hide();
                }
                ;
            });
        })(jQuery);
</script>
