<div class="footer mt50 tac">
    <div class="social">
        <a href="javascript:;"><img src="/web/images/ftx.png"></a>
        <a href="javascript:;"><img src="/web/images/fwx.png"></a>
        <a href="javascript:;"><img src="/web/images/fxl.png"></a>
    </div>
    <p class="mt20"><a href="javascript:;">服务协议</a>丨<a href="javascript:;">运营范围</a>丨<a href="javascript:;">联系邮箱</a>丨<a href="javascript:;">侵权投诉</a></p>
    <p class="mt10 color656">Copyright © 2016-2020 Youhao. All Rights Reserved</p>
</div>