<link href="/web/js/plugins/swiper/swiper-3.3.1.min.css" rel="stylesheet" type="text/css">
<div class="wraper">
    <?php
    $this->partial("commen/header", array('on' => 'index'));
    ?>
    <div class="content">
        <div class="banner">
            <div class=" max1200">
                <div class="loginBox pd40">
                    <p class="title">登录</p>
                    <form class="mt20">
                        <div class="formList">
                            <input type="text" placeholder="帐号：" name="account" />
                        </div>
                        <div class="formList">
                            <input type="password" placeholder="密码：" name="password" />
                        </div>
                        <div class="clearfix mt20">
                            <label class="fl rememberPw"><input type="checkBox" class="displayN" name="rememberPw"/><span class="checkItem yellow"></span><span class="p16 color656">记住密码</span></label>
                            <a href="/login/forget" class="fr p16 color656">忘记密码</a>
                        </div>
                        <a href="javascript:;" class="loginBtn mt20 p16" role="login">立即登录</a>
                        <p class="tac mt20 p16 color656">使用第三方账号登录</p>
                        <div class="socialLogin clearfix mt20">
                            <div class="list">
                                <a href="javascript:;" class="tac color656"><img src="/web/images/weixin.fw.png" /><span class="displayB mt10">微信</span></a>
                            </div>
                            <div class="list">
                                <a href="javascript:;" class="tac color656"><img src="/web/images/qq.fw.png" /><span class="displayB mt10">QQ</span></a>
                            </div>
                            <div class="list">
                                <a href="javascript:;" class="tac color656"><img src="/web/images/weibo.fw.png" /><span class="displayB mt10">微博</span></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="">
                <div class="">
                    <div class="">
                        <div class="">
                            <img src="/web/images/banner.fw.png" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="max1200 mt50 clearfix">
        <div class="produtShow fl">
            <a class="left" href="javascript:;" role="arrowLeft"><img src="/web/images/left.png"></a>
            <a class="right" href="javascript:;" role="arrowRight"><img src="/web/images/right.png"></a>
            <div class="productPic tac">
            	<div class="swiper-container sliderBlock_wrapper" id="swiperApp">
                	<div class="swiper-wrapper">
                    	<div class="swiper-slide">
                			<img src="/web/images/banner2.fw.png">
                        </div>
                        <div class="swiper-slide">
                			<img src="/web/images/banner2.fw.png">
                        </div>
                        <div class="swiper-slide">
                			<img src="/web/images/banner2.fw.png">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="downLoadApp fl tac">
            <h1 class="color018">下载友好APP</h1>
            <p class="p16">在这里您将会找到您需要的人，不需要花费再多时间</p>
            <div class="erweiDownLoad mt50">
                <span class="eriweiBox">
                    <div class="erweiPic">
                        <img src="/web/images/ioserwei.png">
                    </div>
                    <p class="mt20 p18">IOS</p>
                </span>
                <span class="eriweiBox">
                    <div class="erweiPic">
                        <img src="/web/images/androiderwei.png">
                    </div>
                    <p class="mt20 p18">Android</p>
                </span>
            </div>
        </div>
    </div>
    <div class="mt50 bg018">
        <div class="shortLink max1200 tac">
            <h1 class="whiteColor">友好，你的人脉全在这里</h1>
            <div class="linkItem clearfix whiteColor">
                <ul class="clearfix">
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/liwu.png">
                            <p class="p26 mt10">找客户</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/chuizi.png">
                            <p class="p26 mt10">找商机</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/shichang.png">
                            <p class="p26 mt10">找市场</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/renma.png">
                            <p class="p26 mt10">找人脉</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/xiaoyou.png">
                            <p class="p26 mt10">找校友</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>
                    <li>
                        <div class="Itemcontent">
                            <img src="/web/images/laoxiang.png">
                            <p class="p26 mt10">找同乡</p>
                            <p class="mt20">同乡交友等栏目,为各地的同乡提供一个交流、联系的平台</p>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="max1200 mt50 tac clearfix"><!--入驻机构-->
        <h1 class="color018">入驻机构</h1>
        <div class="mechanism">        
            <a class="left" href="javascript:;"><img src="/web/images/left.png"></a>
            <a class="right" href="javascript:;"><img src="/web/images/right.png"></a>
            <ul class="clearfix" role="institution">
            </ul>
        </div>
    </div><!--入驻机构-->
    <hr>

    <div class="max1200 mt50 tac clearfix"><!--热门活动-->
        <h1 class="color018">热门活动</h1>
        <div class="hotActivity">
            <ul class="clearfix" role="activity">
            </ul>
        </div>
    </div><!--热门活动-->
    <?php
    $this->partial("commen/footer");
    ?>
</div>
<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
(function(e){
	if($.cookie('login_account')){
		$('input[name="account"]').val($.cookie('login_account'));
		$('input[name="rememberPw"]').attr('checked',true);
		rpcJSON('decrypt',{password:$.cookie('login_password')},function(backData){
			$('input[name="password"]').val(backData);
		},function(msg){},'/rpc');
	}else{
		$('input[name="rememberPw"]').attr('checked',false);
	};
	$('.wraper').delegate('a[role]',click,function(){
		var $this = $(this),
			role = $this.attr('role');
		switch(role){
			case'login':
                                var data = getFormValue($('form')),
                                        msg='';
                                if(!data.account){
                                        msg='请输入账号';
                                }else if(!data.password){
                                        msg='请输入密码';
                                };
                                if(msg){
                                        Tips('error',msg);
                                }else{
                                        rpcJSON('login',data,function(backData){
                                                if($('input[name="rememberPw"]').prop('checked')){
                                                        $.cookie('login_account',data.account,{expires: 7, path: '/'});
                                                        rpcJSON('encrypt',{password:data.password},function(backData){
                                                                $.cookie('login_password',backData,{expires: 7, path: '/'});
                                                        },function(msg){},'/rpc');
                                                }else{
                                                        $.cookie('login_account',null);
                                                        $.cookie('login_password',null);
                                                };
                                                Tips('success','登陆成功，正在为您跳转',1000,function(){
//                                                        window.location.href='/my';
                                                });
                                        },function(msg){
                                                Tips('error',msg);
                                        },'/loginrpc');
                                };
			break;
		};
		
	});	
	$(document).keydown(function(event){
		if(event.keyCode==13){
			$('a[role="login"]').click();
		}
	 });
	 
	 
	 //swiper
	 var mySwiper = new Swiper('#swiperApp', {
		paginationClickable: true,
		grabCursor: true,
		resizeReInit: true,
		loop:true,
		calculateHeight: true,
		autoplay: 3000,
		speed:2000,
		autoplayDisableOnInteraction:false
	});
	
	$('a[role="arrowLeft"]').on(click, function (e) {
		e.preventDefault();
		mySwiper.slidePrev();
	});
	
	$('a[role="arrowRight"]').on(click, function (e) {
		e.preventDefault();
		mySwiper.slideNext();
	});
	
	//热门活动
	function getActivity(){
		rpcJSON('',{},function(backData){
			var html='';
			if(backData&&backData.length){
				$.each(backData,function(i,item){
					html+='<li>\
						<div class="activityContent">\
							<a href="javascript:;">\
								<img data-src="'+item.pic+'" data-crop="1" />\
								<p class="p22 mt10">'+item.title+'</p>\
								<P class="p16 mt10 color656">'+item.content+'</P>\
							</a>\
						</div>\
					</li>';
				});
			};
			$('[role="activity"]').html(html);
			$('[role="activity"]').find('img').setThumbImageView();
		},function(){
		},'');
	};
	//入住机构
	function getInstitution(){
		rpcJSON('',{},function(backData){
			var html='';
			if(backData&&backData.length){
				$.each(backData,function(i,item){
					html+='<li>\
							<div class="mechanismcontent">\
								<a href="javascript:;">\
									<img data-src="'+item.pic+'">\
									<p class="p16 mt10">'+item.title+'</p>\
								</a>\
							</div>\
						</li>';
				});
			};
			$('[role="institution"]').html(html);
			$('[role="institution"]').find('img').setThumbImageView();
		},function(){
		},'');
	};
})(jQuery)
</script>