<div class="wraper">
    <div class="content">
        <div class="banner">
            <div class=" max1200">
                <div class="loginBox pd40">
                    <div style="max-width: 200px">
                        <ul>
                            <li>个人资料</li>
                            <li>帐号中心</li>
                            <li>工</li>
                            <li>上</li>
                            <li>不</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--            <div class="">
                            <div class="">
                                <div class="">
                                    <div class="">
                                        <img src="/web/images/banner.fw.png" />
                                    </div>
                                </div>
                            </div>
                        </div>-->
        </div>
    </div>
</div>
<script src="/web/js/plupload.full.min.js"></script>
<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {

        });
</script>
