<style>
    #wraper{
        width: 800px;
        height: 500px;
    }
</style>

<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=1e6207365d1676f81c89d86262460cec"></script> 
<div class="wraper" id="wraper">

</div>
<script src="/admin/js/plugins/glDatePicker/glDatePicker.min.js"></script>
<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {
            var map = new AMap.Map('wraper', {
                resizeEnable: true,
                zoom: 10,
                center: [116.397428, 39.90923] //new AMap.LngLat(116.39,39.9)
            });
//            map.setZoom(10);
//            map.setCenter([116.39, 39.9]);
            var marker = new AMap.Marker({
                position: [116.480983, 39.989628], //marker所在的位置
                map: map//创建时直接赋予map属性
            });
            //也可以在创建完成后通过setMap方法执行地图对象
//            marker.setMap(map);
        });
</script>
