<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'vip_terms', 'in' => 'help'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>VIP服务条款</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">标题</div>
                <div class="formListR">
                    <input type="text" class="inputNormal">
                </div>
            </div>
            <div class="formList">
                <div class="formListL">内容</div>
                <div class="formListR">
                    <textarea class="inputNormal" placeholder="富文本"></textarea>
                </div>
            </div>
            <div class="formList mt20">
                <a href="javascript:;" class="mainBtn">确定</a>
            </div>
        </div>
    </div>
</div>