<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'community_manage', 'in' => 'community'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>社团广告</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="topBar clearfix"><!--筛选栏-->
            <div class="screenBar">
                <div class="screenBtn">
                    <a href="javascript:;">批量操作</a>
                    <div class="screenBox">
                        <li>批量删除</li>
                    </div>
                </div>
                <div class="searchBar fl">
                    <input type="text" placeholder="请输入搜索内容">
                    <a href="javascript:;" class="searchBtn">搜索</a>
                </div>
            </div>

        </div><!--筛选栏结束-->
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th width="40px"><label><input type="checkbox"><div class="select"></div></label></th>
                        <th>广告图片</th>
                        <th>广告链接</th>
                        <th>成员人数</th>
                        <th>起止时间</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td class="adv"><img src="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg"></td>
                        <td><a href="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg">http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg</a></td>
                        <td><a href="社团成员.html">12</a></td>
                        <td>
                            <p><span>始：</span>2015/07/07</p>
                            <p><span>末：</span>2015/09/07</p>
                        </td>
                        <td><a href="javascript:;">审核广告</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td class="adv"><img src="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg"></td>
                        <td><a href="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg">http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg</a></td>
                        <td><a href="社团成员.html">12</a></td>
                        <td>
                            <p><span>始：</span>2015/07/07</p>
                            <p><span>末：</span>2015/09/07</p>
                        </td>
                        <td><a href="javascript:;">审核广告</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td class="adv"><img src="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg"></td>
                        <td><a href="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg">http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg</a></td>
                        <td><a href="社团成员.html">12</a></td>
                        <td>
                            <p><span>始：</span>2015/07/07</p>
                            <p><span>末：</span>2015/09/07</p>
                        </td>
                        <td><a href="javascript:;">审核广告</a><a href="javascript:;">删除</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="pageBar">
            <div class="page fr">
                <ul class="clearfix">
                    <li><a href="javascript:;"><i class="icon-left"></i></a></li>
                    <li><a href="javascript:;" class="active">1</a></li>
                    <li><a href="javascript:;">2</a></li>
                    <li><a href="javascript:;">3</a></li>
                    <li><a href="javascript:;">4</a></li>
                    <li><a href="javascript:;"><i class="icon-right"></i></a></li>
                </ul>
            </div>
            <div class="pageBar_num fl"><p class="sFc">共<span class="lFc">2</span>条数据，每页显示
                    <select>
                        <option>10</option>
                    </select>
                    <span>条数据</span>
                </p>
            </div>
        </div>
    </div>
</div>