<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'community_manage', 'in' => 'community'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>编辑社团</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">            
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">LOGO</div>
                <div class="formListR">
                    <div class="pic">
                        <img src="http://e.hiphotos.baidu.com/zhidao/pic/item/241f95cad1c8a786cda7ccb36409c93d71cf50f9.jpg">
                    </div>
                    <a href="javascript:;" class="addBtn"><i class="icon-add"></i></a>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">我的格言</div>
                <div class="formListR">
                    <textarea class="inputNormal" placeholder=""></textarea>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">我的故事</div>
                <div class="formListR">
                    <textarea class="inputNormal" placeholder="富文本"></textarea>
                </div>
            </div>
            <div class="formList mt20">
                <a href="javascript:;" class="mainBtn">保存</a>
            </div>
        </div>
    </div>
</div>