<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'user_notice', 'in' => 'user'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>自动触发通知</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>任务名称</th>
                        <th>类型</th>
                        <th class="geyan">内容</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td>社团推荐信通知</td>
                        <td>自动触发</td>
                        <td>{社团名称}为您写了推荐信，已发给所有成员，快去查看吧！</td>
                        <td><a href="javascript:;">编辑</a></td>
                    </tr>
                    <tr>
                        <td>活动报名审批通知</td>
                        <td>自动触发</td>
                        <td>您的好友{用户中文名英文名}为您写了推荐信，已发给TA所有好友，快去查看吧！...</td>
                        <td><a href="javascript:;"></a></td>
                    </tr>
                    <tr>
                        <td>加入社团审批通知</td>
                        <td>自动触发</td>
                        <td>您报名参加{活动标题}通过/未通过审核，快去查看吧！</td>
                        <td><a href="javascript:;"></a></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="pageBar">
            <div class="page fr">
                <ul class="clearfix">
                    <li><a href="javascript:;"><i class="icon-left"></i></a></li>
                    <li><a href="javascript:;" class="active">1</a></li>
                    <li><a href="javascript:;">2</a></li>
                    <li><a href="javascript:;">3</a></li>
                    <li><a href="javascript:;">4</a></li>
                    <li><a href="javascript:;"><i class="icon-right"></i></a></li>
                </ul>
            </div>
            <div class="pageBar_num fl"><p class="sFc">共<span class="lFc">2</span>条数据，每页显示
                    <select>
                        <option>10</option>
                    </select>
                    <span>条数据</span>
                </p>
            </div>
        </div>
    </div>
</div>