<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'user_ordinary', 'in' => 'user'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>编辑会员</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="itemTitle">
            个人资料
        </div>
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">头像</div>
                <div class="formListR">
                    <div class="pic">
                        <img src="http://desk.fd.zol-img.com.cn/t_s960x600c5/g5/M00/01/0E/ChMkJlbKwhKIXmKmABXUcO-fCzIAALGiQKzwv4AFdSI694.jpg">
                    </div>
                    <a href="javascript:;" class="mainBtn">更换头像</a>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">账号</div>
                <div class="formListR">13559993640</div>
            </div>
            <div class="formList">
                <div class="formListL">性别</div>
                <div class="formListR">
                    <label><input type="radio" name="sex" checked value="男">男</label>
                    <label><input type="radio" name="sex" value="女">女</label>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">中文名</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">英文名</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">居住地</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">籍贯</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
        </div>

        <div class="itemTitle">
            公司资料
        </div>
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">公司名称</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">行业</div>
                <div class="formListR">
                    <select>
                        <option>行业1</option>
                        <option>行业2</option>
                    </select>
                </div>
            </div>
            <div class="formList">
                <div class="formListL">公司职务</div>
                <div class="formListR">
                    <select>
                        <option>职业1</option>
                        <option>职业2</option>
                    </select>
                </div> 
            </div>
            <div class="formList">
                <div class="formListL">公司介绍</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">公司图片</div>
                <div class="formListR">
                    <div class="companyPic">
                        <img src="http://desk.fd.zol-img.com.cn/t_s960x600c5/g5/M00/01/0E/ChMkJlbKwhKIXmKmABXUcO-fCzIAALGiQKzwv4AFdSI694.jpg">
                    </div>
                    <a href="javascript:;" class="addBtn"><i class="icon-add"></i></a>
                </div>
            </div>
        </div>

        <div class="itemTitle">
            联系信息
        </div>
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="formListL">手机</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">邮箱</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">联系地址</div>
                <div class="formListR"><input type="text" class="inputNormal"></div> 
            </div>
            <div class="formList">
                <div class="formListL">助理姓名</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
            <div class="formList">
                <div class="formListL">助理电话</div>
                <div class="formListR"><input type="text" class="inputNormal"></div>
            </div>
        </div>
        <div class="itemTitle">
            学校资料
        </div>
        <div class="editInfo clearfix">
            <div class="formList">
                <div class="schoolLeft">学校一</div>
                <div class="schoolRight"><a href="javascript:;"><i class="icon-delete"></i></a></div>
            </div>
            <div class="formList">
                <div class="schoolLeft">学校一</div>
                <div class="schoolRight"><a href="javascript:;"><i class="icon-delete"></i></a></div>
            </div>
            <div class="formList">
                <div class="schoolLeft">学校一</div>
                <div class="schoolRight"><a href="javascript:;"><i class="icon-delete"></i></a></div>
            </div>
            <div class="formList mt20">
                <a href="javascript:;" class="mainBtn">确定修改</a>
            </div>
        </div>
    </div>
</div>