<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'user_news', 'in' => 'user'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>会员动态管理</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="topBar clearfix"><!--筛选栏-->
            <div class="screenBar">
                <div class="screenBtn">
                    <a href="javascript:;">批量操作</a>
                    <div class="screenBox">
                        <li>批量删除</li>
                    </div>
                </div>
                <div class="screenBtn">
                    <a href="javascript:;">全部类型</a>
                    <div class="screenBox">
                        <li>个人动态</li>
                        <li>好友推荐信</li>
                        <li>社团推荐信</li>
                    </div>
                </div>
                <div class="searchBar fl">
                    <input type="text" placeholder="请输入搜索内容">
                    <a href="javascript:;" class="searchBtn">搜索</a>
                </div>
            </div>
        </div><!--筛选栏结束-->
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th width="40px"><label><input type="checkbox"><div class="select"></div></label></th>
                        <th>账号</th>
                        <th>中文名</th>
                        <th>英文名</th>
                        <th>类型</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>13856953600</td>
                        <td>孙悟空</td>
                        <td>Mr.sun</td>
                        <td>社团推荐信</td>
                        <td><a href="/admin/userNewsInfo">查看</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>13856953600</td>
                        <td>孙悟空</td>
                        <td>Mr.sun</td>
                        <td>好友推荐信</td>
                        <td><a href="/admin/userNewsInfo">查看</a><a href="javascript:;">删除</a></td>
                    </tr>
                    <tr>
                        <td><label><input type="checkbox"><div class="select"></div></label></td>
                        <td>13856953600</td>
                        <td>孙悟空</td>
                        <td>Mr.sun</td>
                        <td>个人动态</td>
                        <td><a href="/admin/userNewsInfo">查看</a><a href="javascript:;">删除</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>