<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'user_QR', 'in' => 'user'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>张三的注册用户</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="topBar clearfix"><!--筛选栏-->
            <div class="screenBar">
                <div class="screenBtn">
                    <a href="javascript:;">全部用户</a>
                    <div class="screenBox">
                        <li>VIP</li>
                        <li>普通会员</li>
                    </div>
                </div>
                <div class="searchBar fl">
                    <input type="text" placeholder="请输入搜索内容">
                    <a href="javascript:;" class="searchBtn">搜索</a>
                </div>
            </div>
        </div><!--筛选栏结束-->
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>账号</th>
                        <th>创建社团</th>
                        <th>注册时间</th>
                        <th>是否VIP</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td>13559993640</td>
                        <td>3</td>
                        <td>2016/12/12</td>
                        <td>是</td>
                    </tr>
                    <tr>
                        <td>13559993640</td>
                        <td>3</td>
                        <td>2016/12/12</td>
                        <td>否</td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="pageBar">
            <div class="page fr">
                <ul class="clearfix">
                    <li><a href="javascript:;"><i class="icon-left"></i></a></li>
                    <li><a href="javascript:;" class="active">1</a></li>
                    <li><a href="javascript:;">2</a></li>
                    <li><a href="javascript:;">3</a></li>
                    <li><a href="javascript:;">4</a></li>
                    <li><a href="javascript:;"><i class="icon-right"></i></a></li>
                </ul>
            </div>
            <div class="pageBar_num fl"><p class="sFc">共<span class="lFc">2</span>条数据，每页显示
                    <select>
                        <option>10</option>
                    </select>
                    <span>条数据</span>
                </p>
            </div>
        </div>
    </div>
</div>