<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'user_QR', 'in' => 'user'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>二维码管理</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="topBar clearfix"><!--筛选栏-->
            <div class="screenBar">
                <div class="timePicker fl">
                    <input type="date" placeholder="开始时间"><span class="color999"> — </span><input type="date" placeholder="结束时间">
                    <a href="javascript:;" class="searchBtn">确定</a>
                </div>

                <div class="searchBar fl">
                    <input type="text" placeholder="请输入搜索内容">
                    <a href="javascript:;" class="searchBtn">搜索</a>
                </div>
            </div>
        </div><!--筛选栏结束-->
        <div class="tableBox">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>账号</th>
                        <th>中文名</th>
                        <th>英文名</th>
                        <th>注册用户（VIP）</th>
                        <th>注册社团（总人数）</th>
                        <th>VIP二维码订单（总金额）</th>
                    </tr>
                </thead>
                <tbody class="tac">
                    <tr>
                        <td>13856953600</td>
                        <td>孙悟空</td>
                        <td>Mr.sun</td>
                        <td><a href="/admin/userRegistered">3（2）</a></td>
                        <td><a href="/admin/communityRegistered">12（120）</a></td>
                        <td><a href="/admin/vipQROrder">12（120）</a></td>
                    </tr>
                    <tr>
                        <td>13856953600</td>
                        <td>孙悟空</td>
                        <td>Mr.sun</td>
                        <td><a href="/admin/userRegistered">3（2）</a></td>
                        <td><a href="/admin/communityRegistered">12（120）</a></td>
                        <td><a href="/admin/vipQROrder">12（120）</a></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="pageBar">
            <div class="page fr">
                <ul class="clearfix">
                    <li><a href="javascript:;"><i class="icon-left"></i></a></li>
                    <li><a href="javascript:;" class="active">1</a></li>
                    <li><a href="javascript:;">2</a></li>
                    <li><a href="javascript:;">3</a></li>
                    <li><a href="javascript:;">4</a></li>
                    <li><a href="javascript:;"><i class="icon-right"></i></a></li>
                </ul>
            </div>
            <div class="pageBar_num fl"><p class="sFc">共<span class="lFc">2</span>条数据，每页显示
                    <select>
                        <option>10</option>
                    </select>
                    <span>条数据</span>
                </p>
            </div>
        </div>
    </div>
</div>