<link href="/web/js/plugins/swiper/swiper-3.3.1.min.css" rel="stylesheet" type="text/css">
<div class="wraper" id="wraper">
    <div class="formListL">
        <a href="javascript:;" class="user_photo"><img id="photpsrc" src="" /></a>
    </div>
    <div class="formListR">
        <p id="uploadmsg">最佳尺寸 60px*60px</p>
        <p><a href="javascript:;" id="photpsrc" class="redFc">上传头像</a></p>
    </div>
    <div id="uploads"><a href="javascript:;" class="mainBtn ml10" id="upload">上传会员</a></div>
</div>
<!--使用七牛-->
<!--<script src="/admin/js/plugins/plupload/moxie.js"></script>
<script src="/admin/js/plugins/plupload/plupload.dev.js"></script>
<script src="/admin/js/plugins/plupload/qiniu.js"></script>-->
<!--使用plupload-->
<script src="/admin/js/plugins/plupload/plupload.full.min.js"></script>
<script src="/admin/js/plugins/plupload/qiniu.js"></script>
<script src="/admin/js/upload.js" type="text/javascript"></script>
<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {
                var type = '<?php echo $type; ?>', url = '';
                switch (type)
                {
                        case 'file':
                            url = '/admin/upload/file';
                            break;
                        case 'resource':
                            url = '/admin/upload/resource';
                            break;
                        case 'local':
                            url = '/admin/upload/local';
                            break;
                        case 'exportIn':
                            url = '/admin/excel/exportIn';
                            break;
                        case 'exportOut':
                            url = '/admin/excel/exportOut';
                            break;
                }
//                var uploader = Qiniu.uploader({
//                                runtimes: 'html5,flash,silverlight,html4',    //上传模式,依次退化
//                                browse_button: 'upload',       //上传选择的点选按钮，**必需**
//                                uptoken_url: '/admin/upload/uptoken',            //Ajax请求upToken的Url，**强烈建议设置**（服务端提供）
////                                 uptoken : '<Your upload token>', //若未指定uptoken_url,则必须指定 uptoken ,uptoken由其他程序生成
//                                // unique_names: true, // 默认 false，key为文件名。若开启该选项，SDK为自动生成上传成功后的key（文件名）。
//                                // save_key: true,   // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK会忽略对key的处理
//                                domain: 'http://oj13vjytx.bkt.clouddn.com/',   //bucket 域名，下载资源时用到，**必需**
//                                get_new_uptoken: false,  //设置上传文件的时候是否每次都重新获取新的token
//                                container: 'wraper',           //上传区域DOM ID，默认是browser_button的父元素，
//                                max_file_size: '100mb',           //最大文件体积限制
//                                flash_swf_url: '/admin/js/plugins/plupload/Moxie.swf',  //引入flash,相对路径
//                                silverlight_xap_url: '/admin/js/plugins/plupload/Moxie.xap',
//                                max_retries: 3,                   //上传失败最大重试次数
//                                dragdrop: true,                   //开启可拖曳上传
//                                drop_element: 'wraper',        //拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
//                                chunk_size: '4mb',                //分块上传时，每片的体积
//                                auto_start: true,                 //选择文件后自动上传，若关闭需要自己绑定事件触发上传
//                                init: {
//                                        FilesAdded: function(up, files) {
//                                                plupload.each(files, function(file) {
//                                                    // 文件添加进队列后,处理相关的事情
//                                                });
//                                        },
//                                        BeforeUpload: function(up, file) {
//                                               // 每个文件上传前,处理相关的事情
//                                        },
//                                        UploadProgress: function(up, file) {
//                                               // 每个文件上传时,处理相关的事情
//                                        },
//                                        FileUploaded: function(up, file, info) {
//                                               // 每个文件上传成功后,处理相关的事情
//                                               // 其中 info 是文件上传成功后，服务端返回的json，形式如
//                                               // {
//                                               //    "hash": "Fh8xVqod2MQ1mocfI4S4KpRL6D98",
//                                               //    "key": "gogopher.jpg"
//                                               //  }
//                                               // 参考http://developer.qiniu.com/docs/v6/api/overview/up/response/simple-response.html
//
//                                               // var domain = up.getOption('domain');
//                                               // var res = parseJSON(info);
//                                               // var sourceLink = domain + res.key; 获取上传成功后的文件的Url
//                                        },
//                                        Error: function(up, err, errTip) {
//                                               //上传出错时,处理相关的事情
//                                        },
//                                        UploadComplete: function() {
//                                               //队列文件处理完毕后,处理相关的事情
//                                        },
//                                        Key: function(up, file) {
//                                                // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
//                                                // 该配置必须要在 unique_names: false , save_key: false 时才生效
//
//                                                var key = "";
//                                                // do something with key here
//                                                return key;
//                                        }
//                                }
//                        });
            
            qiniuUpload();
//            upload({
//                    extensions:'jpg,png,jpeg,gif,apk',
//                    max_file_size:'50mb',
//                    url:url
//            });
        });
</script>
