
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="format-detection" content="telephone=no" />                
        <?php echo $this->tag->getTitle(); ?>
        <link href="/web/css/style.css" rel="stylesheet" type="text/css">
        <link href="/web/css/private.css" rel="stylesheet" type="text/css">
        <link href="/web/css/dialog.css" rel="stylesheet" type="text/css">
        <link href="/web/css/iconfont.css" rel="stylesheet" type="text/css">
        <script src="/web/js/jquery.min.js" type="text/javascript"></script>
        <script src="/web/js/jquery.easing.compatibility.js"></script>
<!--        <script src="/web/js/jquery.cookie.js" type="text/javascript"></script>-->
         <!--<script src="/web/js/jqPaginator.min.js" type="text/javascript"></script>-->
        <!--<script src="/web/js/siteText.js"></script>-->
        <script src="/web/js/common.js"></script>
        <script src="/web/js/phprpc.js"></script>
        <!--<script src="/web/js/dialog.js"></script>-->
        <script src="/web/js/forms.js"></script>
        
    </head>
    <body>
        <?php echo $this->getContent(); ?>
    </body>

</html>
