
<?php
$this->partial("commen/header");
?>
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
        <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
                <meta name="description" content="bootstrap admin template">
                <meta name="author" content="">

                <title>拜拜 | 您没有操作权限</title>
                <!--[if lt IE 9]>
                  <script src="../../assets/vendor/html5shiv/html5shiv.min.js"></script>
                  <![endif]-->

                <!--[if lt IE 10]>
                  <script src="../../assets/vendor/media-match/media.match.min.js"></script>
                  <script src="../../assets/vendor/respond/respond.min.js"></script>
                  <![endif]-->

                <script>
                        Breakpoints();
                </script>
        </head>
        <body class="page-error page-error-404 layout-full">
                <!--[if lt IE 8]>
                      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
                  <![endif]-->
                <!-- Page -->
                <div class="page animsition vertical-align text-center" data-animsition-in="fade-in"
                     data-animsition-out="fade-out">
                        <div class="page-content vertical-align-middle">
                                <header>
                                        <h1 class="animation-slide-top">拜拜</h1>
                                        <p>您没有操作权限 !</p>
                                </header>
                                <p class="error-advise">去找回权限</p>
                                <a class="btn btn-primary btn-round" href="/index">GO</a>
                        </div>
                </div>
                <!-- End Page -->
                <script>
                        (function(document, window, $) {
                                'use strict';
                                var Site = window.Site;
                                $(document).ready(function() {
                                        Site.run();
                                });
                        })(document, window, jQuery);
                </script>


        </body>

</html>