<style>
    .dialog{
        position: fixed;
        /*background: #00FF00;*/
        width: 100%;height: 100%;
        text-align: center;
        z-index: 99;
    }
    .content{
        margin: 10% auto;
        width: 20%;
        background: #656565;
    }
    .head{
        background-color: red;
        height: 50px;line-height: 50px;
        font-size: 20px;
    }
    .body{
        font-size: 16px;
        padding-top: 20px;padding-bottom: 20px;
    }
    .tip{
        font-weight: bold;
        margin: 10px 0 10px 0;
    }
    .second{
        margin: 10px 0 10px 0;
    }
</style>
<div class="dialog">
    <div class="content">
        <div class="head">标题</div>
        <div class="body">
            <div class="tip">提示</div>
            <div class="second"><span>6</span>秒灵敏</div>
        </div>
    </div>
</div>
<script>
        $(function(){
                var sec = $('.second').children('span');
                var time = setInterval(delay,1000);
                function delay()
                {
                        var t = sec.text()-1;
                        sec.text(t);
                        if(parseInt(t)<=0)
                        {
                                clearInterval(time);
                        }
                };
        });
</script>