<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'statistics_income', 'in' => 'statistics'));
    ?>
</div>
<div class="mainContent">
    <div class="mainTitle">
        <span>收入统计</span><span><a href="javascript:;" class="fr p12">退出登录</a></span>
    </div>
    <div class="mainData">
        <div class="twoCloumn overLength clearfix">
            <ul>
                <li>
                    <div class="textBox">
                        <div class="leftText">注册用户总数</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">社团总数</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">激活用户总数</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">VIP订单总数</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日总收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日置顶收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日广告收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日VIP收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日短信收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日小秘书收入</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日激活用户总数</div><div class="rightText">32</div>
                    </div>
                </li>
                <li>
                    <div class="textBox">
                        <div class="leftText">昨日VIP用户订单总数</div><div class="rightText">32</div>
                    </div>
                </li>                    
            </ul>
        </div>
    </div>
</div>