<div class="leftBar">
    <div class="logo tac">
        <a href="javascript:;">
            <img src="/admin/images/logo.png">
        </a>
    </div>
    <?php
    $this->partial("admin/left", array('on' => 'manager_list', 'in' => 'manager'));
    ?>
</div>
<div class="mainData">            
    <div class="editInfo clearfix">
        <div class="formList">
            <div class="formListL">管理员账号</div>
            <div class="formListR">
                <input type="text" class="inputNormal" placeholder="">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">姓名</div>
            <div class="formListR">
                <input type="text" class="inputNormal" placeholder="">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">密码</div>
            <div class="formListR">
                <input type="password" class="inputNormal" placeholder="">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">确认密码</div>
            <div class="formListR">
                <input type="password" class="inputNormal" placeholder="">
            </div>
        </div>
        <div class="formList">
            <div class="formListL">角色</div>
            <div class="formListR">
                <select>
                    <option>某某管理员</option>
                </select>
            </div>
        </div>
        <div class="formList mt20">
            <a href="javascript:;" class="mainBtn">确定</a>
        </div>
    </div>
</div>