
<!doctype html>
<html style="height: 100%">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="format-detection" content="telephone=no" />                
        <?php echo $this->tag->getTitle(); ?>
        <link href="/admin/css/private.css" type="text/css" rel="stylesheet">
        <link href="/admin/css/style.css" type="text/css" rel="stylesheet">
        <link href="/admin/css/iconfont.css" type="text/css" rel="stylesheet">
        <link href="/admin/css/iframe.css" type="text/css" rel="stylesheet"><!--右侧弹框-->
        <link href="/admin/css/leftNav.css" type="text/css" rel="stylesheet"><!--左侧菜单-->
        <link href="/admin/css/tips.css" type="text/css" rel="stylesheet"><!--警告，JS在common.js中-->
        <link href="/admin/css/dialog.css" type="text/css" rel="stylesheet"><!--对话框-->
        <script src="/admin/js/jquery-1.9.1.js" type="text/javascript"></script>
        <script src="/web/js/jquery.easing.compatibility.js"></script><!--小图标-->
        <script src="/admin/js/common.js" type="text/javascript"></script>
        <script src="/admin/js/phprpc.js" type="text/javascript"></script><!--rpc文件-->
        <script src="/admin/js/forms.js" type="text/javascript"></script><!--表单-->
        <script src="/admin/js/dialog.js" type="text/javascript"></script><!--对话框-->
        <script src="/admin/js/iframe.js" type="text/javascript"></script><!--右侧弹框-->
        
    </head>
    <body style="height: 100%">
        <?php echo $this->getContent(); ?>
    </body>

</html>
