<link href="/web/js/plugins/swiper/swiper-3.3.1.min.css" rel="stylesheet" type="text/css">
<style>
    .leftNav{width: 100%;height: 100px;padding-left: 30px;}
    .pl{padding-left: 60px;}
</style>
<div>
    <a href="javascript:;" role="word">这是一个word文档</a>
</div>
<script src="/web/js/plugins/swiper/swiper-3.3.1.jquery.min.js" type="text/javascript"></script>
<script>
        $(function () {
                $('a[role="word"]').click(function(){
                        window.location.href = '/admin/preview/preword';
                });
        });
</script>