<html>
        <head>
                <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/> 
                <title>微信支付</title>
                <style>
                        body{
                                background:#f1f1f1;
                        }
                        .weixinPay{
                                text-align:center;
                                padding-top:50px;
                        }
                        .weixinPay font{
                                font-size:12px;
                                color:#666;
                        }
                        .weixinPay span{
                                display:block;
                                font-size:25px;
                                margin-top:10px;
                        }
                        .weixinPay button{
                                background-color: #dd0000;
                                margin-top:20px;
                                color: #fff;
                                display: inline-block;
                                text-align: center;
                                padding: 0 30px;
                                font-size: 14px;
                                line-height: 36px;
                                border-radius: 2px;
                                vertical-align: middle;
                                text-decoration:none;
                                border:0;
                        }
                </style>
        </head>
        <body>
                <div class="weixinPay">
                        <br/>
                        <font>该笔订单支付金额为<span style="display:block;"><?php echo $total_fee; ?></span></font><br/><br/>
                        <div align="center">
                                <img src="/index/qRcode?content=<?php echo $url; ?>">
                                <!--<button style="cursor: pointer;" type="button" onclick="callpay()" >立即支付</button>-->
                        </div>
                </div>
        </body
</html>