
<div class="bgf1f1">
    <div class="wraper" id="wraper">
        <?php
        $this->partial("commen/header", array('on' => 'client'));
        ?>
        <div class="navShadow">
        </div>
        <div class="content">
            <div class="headBar max1200 clearfix">
                <?php $this->partial("commen/user"); ?>
                <div class="footNav fr color999">
                    <span>我的位置</span>><span>意向客户</span>><span><a href="javascript:;">关注我的人</a></span>
                </div>
            </div>
            <div class="max1200 mainContent bgWhite">
                <div class="mainContentHead">
                    <div class="tabs">
                        <ul class="p18">
                            <li><a href="/client">关注我的人</a></li>
                            <li class="active"><a href="/client/supply">我的供求</a></li>
                            <li><a href="/client/set">链接设置</a></li>
                        </ul>
                    </div>
                </div>

                <div class="vipContent"> <!--主体模块-->
                    <div class="vipTable">
                        <table width="100%">
                            <thead>
                                <tr class="p16 bgf5f5">
                                    <th>用户名</th>
                                    <th>查看时间</th>
                                    <th>是否收藏</th>
                                    <th>备注</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
        <?php
		$this->partial("commen/footer");
		?>
    </div>
</div>
<script>
(function(){
	var url = urlToJson(windowURL),
		id = url.id;
	if(id){
		rpcJSON('supplyDetail',{id:id},function(backData){
			var html='';
			if(backData&&backData.length){
				$.each(backData,function(i,item){
					html+='<tr data-id="'+item.id+'">\
							  <td><a role="userName" class="color018">'+item.name+'</a></td>\
							  <td>'+item.addtime+'</td>\
							  <td>'+item.collection+'</td>\
							  <td><a href="javascript:;" class="ffaHover" role="remMarks">'+item.remarks+'</a></td>\
							  <td><a href="javascript:;" class="ffaHover" role="delete">删除</a></td>\
						  </tr>';
				});
			};
			$('tbody').html(html);
		},function(msg){
			Tips('error',msg);
		},'/clientrpc');
		
		$('.content').delegate('a[role]',click,function(){
			var $this = $(this),
				role = $this.attr('role');
			switch(role){
				case'remMarks':
					var content = $this.text();
					var DialogEl = $('<div><form><textarea class="remMarks" name="remarks" value="'+content+'">'+content+'</textarea></form></div>');
					Confirm(DialogEl, function () {
						var data = getFormValue($('form', DialogEl)),
							id = $this.parents('tr:first').data('id');
		                if (!data.remarks) {
                       	 Tips('error', '请输入备注');
                        }else{
						  data.id=id;
						  rpcJSON('editDetail',data,function(){
							  Tips('success','添加成功',500,function(){
								  $this.text(data.remarks);
							  });
						  },function(msg){
							  Tips('error',msg||'添加失败')
						  },'/clientrpc');
						};
					}, '', {
					   width: 420,
	                   title: "添加备注"
					});
				break;
				case'delete':
					var id = $this.parents('tr:first').data('id');
					Confirm('确认删除该记录？', function () {
						rpcJSON('delDetail', {id:id}, function () {
							Tips("success", "删除成功", 500, function () {
								$this.parents('tr:first').remove();
							});
						}, function (msg) {
							Tips('error', msg);
						}, '/clientrpc');
						},'',{
						   width: 420,
		                   title: "确认删除"
					});
				break;
			}
		});
	};
})(jQuery);
</script>
